### ISSUE TITLE
GVT-g with libvirt XML issues

### ISSUE THREAD

**Issue by digitalsanity** [patmagauran/i915ovmfPkg#13]
Trying to get GVT-g working correctly via virt-manager/libvirt.

I can't seem to figure out how to pass x-igd-opregion properly?

When I set display=on, the mdev complains about missing opengl.  Should I use egl-headless, spice or what's the fastest option here?  egl-headless should be the fastest over VNC?

The default/sample libvirt config seemed to put the device at the wrong location?

I see "Display" with Intel and the correct vendor/device-id in OS X.  How do I get this to correctly report Intel HD Graphics 5500?  I believe this may be related to the PCI device arrangement?

Using baremetal VFIO-PCI passthrough for low latency projects in the past, the best performance can be had by replicating a real PCIe layout.  It looks like the sample config is using PCI instead of PCIe, and perhaps some of the CPU options aren't the best?  Could this be why OS X doesn't detect the actual name of the card and just shows "Display" now?  Is "Display" what you get, and is that why acceleration is not working?

So many questions .. I don't expect anyone here to answer them all .. just looking for a place to document testing.

**Comment by patmagauran** [comment]
You may have to use the qemu:args section of the libvirt xml for this, manually passing the device settings in.

I do not know.

That is possible.

From what I remember, there are some opencore/Clover config options in order to properly get the correct id. 

My test scripts, and many samples use the i440fx chipset which does not have native pcie support. It is more compatible with most systems, but macOS requires q35. 

I reccomend you read the OSX-KVM documentation, as well as the Dortania(For your specific system), as well as the official OpenCore documentation. Hopefully that will help you with a few of these issues.
